### ISSUE TITLE
nrpe_user directive in nrpe-3.0 on AIX ignored

### ISSUE THREAD

**Issue by bahaines** [NagiosEnterprises/nrpe#48] opened 2016-08-09 19:31 UTC
AIX version is: 7100-04-01-1543

I have recently attempted to update our nrpe agent/daemon on our AIX systems. 

Previously we were running:
Version: 2.5.1
Last Modified: 04-09-2006

Now, we are running:
Version: nrpe-3.0
Last Modified: 07-12-2016

When starting the nrpe daemon, it stays running as "root" regardless of the nrpe_user in the nrpe.cfg file.  This issue seems very similar to: [Issue #40 ](https://github.com/NagiosEnterprises/nrpe/issues/40), but seems that RC2 was supposed to have the fix (and John Frickson confirmed).

As shown here, on startup, the nrpe process starts as "root", but the contents of the nrpe.cfg file have nrpe_user and nrpe_group as nagios.

The only way (seemingly) that I can get it to run as nagios is if I do a su.

```
root@hostname:/root>/etc/rc.d/init.d/nrpe start
Starting NRPE daemon... done.
root@hostname:/root>ps -ef | grep nrpe
    root 18808878        1   0 17:47:05      -  0:00 /usr/local/nagios/bin/nrpe -n -c /usr/local/nagios/etc/nrpe.cfg -d
root@hostname:/root>cat /usr/local/nagios/etc/nrpe.cfg | egrep 'nrpe_user|nrpe_group'
nrpe_user=nagios
nrpe_group=nagios
root@hostname:/root>/etc/rc.d/init.d/nrpe stop
Stopping NRPE daemon... done.
root@hostname:/root>su - nagios -c "/etc/rc.d/init.d/nrpe start"
Starting NRPE daemon... done.
root@aubues1:/root>ps -ef | grep nrpe
  nagios 13238330        1   0 17:48:14      -  0:00 /usr/local/nagios/bin/nrpe -n -c /usr/local/nagios/etc/nrpe.cfg -d
```

**Comment by jfrickson** [comment] 2016-12-05 20:10
@bahaines I'm kind of grasping at straws here, but instead of running:
`${PROG_BIN} -n -c ${NRPE_CONFIG} -d`
try using:
`${PROG_BIN} -n -c ${NRPE_CONFIG} -d -s`
(Add the `-s` at the end). And let me know if that works.

**Comment by bahaines** [comment] 2016-12-05 20:29
@jfrickson  I saw your eMail John, I'm sorry I didn't have time to try this until now.

Introducing the "-s" causes strange behavior in AIX.  It looks like it fixes the issue with the proc, but the cursor doesn't return to the terminal.

$ /etc/rc.d/init.d/nrpe start
Starting NRPE daemon... 
(BLINKING CURSOR)

If I open a different session, I see the process and it is running as nagios.

user@hostname:/home/>ps -ef | grep nrp
  nagios 21233702  9633948   0 20:24:57  pts/1  0:00 /usr/local/nagios/bin/nrpe -n -c /usr/local/nagios/etc/nrpe.cfg -d -s

If I do it as "nohup" with & on the process, it is fine:
nagios$:nohup /etc/rc.d/init.d/nrpe start&

nagios$:ps -ef | grep nrpe
  nagios 23003370 21233714   0 20:28:15  pts/1  0:00 /usr/local/nagios/bin/nrpe -n -c /usr/local/nagios/etc/nrpe.cfg -d -s

**Comment by jfrickson** [comment] 2016-12-05 20:36
Looks like straw grasping worked :-)

The `-s` parameter tells nrpe to run as a subsystem under AIX. As far as I can tell, that just means, don't fork.

Change your init script to include the `-s` and you should be all set.

**Comment by jfrickson** [comment] 2016-12-06 17:04
Apparently still a problem. Reopening.

**Comment by jfrickson** [comment] 2017-03-31 19:37
I've worked on this several times, and have been unable to reproduce the problem, or to come up with a solution. I'm going to close the issue, but tag it with the `archive/future` tag so I can possibly come back to it at a later time.

**Closed by jfrickson** 2017-03-31 19:37 UTC
Labels: archive/future, bug
